
name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --scan

    - name: Pack Zip with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: packageFullGame

    - name: Distribute artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/distributions/CrafterLatestRelease.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest release"
        file_glob: true





