
name: Package Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Build release artifact
      uses: gradle/gradle-build-action@v2
      with:
        arguments: startShadowScripts

    - name: Pack Zip with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: packageFullGame

    - name: Distribute artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/distributions/CrafterLatestRelease.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest release"
        file_glob: true





