# Checks each commit to master repo.

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan

      - name: Archive live jar
        uses: actions/upload-artifact@v2
        with:
          name: Crafter-Continuous
          path: build/libs

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: Test Report
          path: build/reports/tests/test