# Checks each commit to master repo.

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Test project
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build live branch artifact
        uses: gradle/gradle-build-action@v2
        with:
          arguments: startShadowScripts

      - name: Archive live jar
        uses: actions/upload-artifact@v3
        with:
          name: Crafter
          path: build/libs

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: build/reports/tests/test