# Checks each commit to master repo.

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up Oracle OpenJDK 17
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 17

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test --scan

      - name: Build live branch artifact
        uses: gradle/gradle-build-action@v2
        with:
          arguments: startShadowScripts --scan

      - name: Archive live jar
        uses: actions/upload-artifact@v3
        with:
          name: Crafter
          path: build/libs

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test Report
          path: build/reports/tests/test